#!/usr/bin/env python

import sys,json
import urllib, urllib2
import base64
import hmac
import hashlib

api_key = "your_api_key"
sec_key = "your_secret_key"

base_url = "http://your_management_ip:8080/client/api"

args = dict([arg.split("=") for arg in sys.argv[1:]])

def gen_url(cmd):
  param = ''
  cmd = args.copy()
  cmd['apiKey'] = api_key

  # sorting hash keys
  for key in sorted(cmd):
    param += key + '=' + urllib.quote(cmd[key]) + '&'
  param = param[:-1]

  # transate to lower case
  param = param.lower()

  # generate digest
  hashed = hmac.new(sec_key, param, hashlib.sha1)
  signature = base64.b64encode(hashed.digest())
  query = urllib.urlencode(args) \
                 + '&apiKey=' + api_key \
                 + '&signature=' + urllib.quote(signature)

  # return integrated URL
  return base_url,query

if __name__ == "__main__":
  url,query = gen_url(args)

  try:
    response = urllib2.urlopen(url, query).read()
    print response
  except urllib2.HTTPError, e:
    print e.read()
